language: python
python:
  - "2.7"

sudo: false
os:
  - linux

before_install:
  - pip install --upgrade pip setuptools Cython

script:
  - git clone https://github.com/googlei18n/noto-source.git
  - cd noto-source
  - fontmake -i -g src/NotoSansArmenian-MM.glyphs
