language: python
python:
  - "2.7"
  - "3.5"

sudo: false
os:
  - linux
  - osx

install:
  - pip install --user -r requirements.txt
  - python setup.py install

script:
  - git clone https://github.com/googlei18n/noto-source.git
  - cd noto-source
  - fontmake -i -g src/NotoSansArmenian-MM.glyphs
