language: python
python:
  - "2.7"

sudo: false
os:
  - linux

install:
  # for fontmake
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - python setup.py install

script:
  - cd test && ./run.sh
